version: 2.1

executors:
  python:
    parameters:
      image_tag:
        type: string
    docker:
      - image: circleci/python:<< parameters.image_tag >>

commands:
  installation:
    steps:
      - checkout
      - run:
          name: Installation
          command: |
            python setup.py sdist
            PACKAGE=$(python setup.py --fullname)
            tar -zxvf dist/${PACKAGE}.tar.gz
            mv ${PACKAGE} package
            virtualenv python -q
            source python/bin/activate
            pip install -e package --progress-bar off
            pip install -r package/test-requirements.txt --progress-bar off
jobs:
  Lint Tests:
    parameters:
      image_tag:
        type: string
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: Lint Tests
          command: |
            source python/bin/activate
            make -C package lint-tests --makefile ../Makefile
  Unit Tests:
    parameters:
      image_tag:
        type: string
      codecov:
        type: boolean
        default: false
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: Unit Tests
          command: |
            source python/bin/activate
            make -C package unit-tests --makefile ../Makefile
      - when:
          condition:
            equal: [ "3.6", << parameters.image_tag >> ]
          steps:
            - run:
                name: Code Coverage
                command: |
                  source python/bin/activate
                  cd package
                  codecov
  Entry Point Test:
    parameters:
      image_tag:
        type: string
    executor:
      name: python
      image_tag: << parameters.image_tag >>
    steps:
      - installation
      - run:
          name: Entry Point Test
          command: |
            source python/bin/activate
            make -C package entry-point-test --makefile ../Makefile
workflows:
  version: 2
  Integration Tests:
    jobs:
      - Lint Tests:
          matrix:
            parameters:
              image_tag: ["3.6", "3.7", "3.8"]
            name: Py<<matrix.image_tag>> - Lint Tests
      - Unit Tests:
          matrix:
            parameters:
              image_tag: ["3.6", "3.7", "3.8"]
            name: Py<<matrix.image_tag>> - Unit Tests
      - Entry Point Test:
          matrix:
            parameters:
              image_tag: ["3.6", "3.7", "3.8"]
            name: Py<<matrix.image_tag>> - Entry Point Test
